language: python

matrix:
  include:
  - os: linux
    dist: trusty
    python: 3.5
  - os: linux
    dist: trusty
    python: 3.6
  - os: linux
    dist: xenial
    python: 3.7

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew upgrade python3
    python3 --version
    python3 -m pip install -U pip
    which pip3
  fi

install:
  - pip3 install -r requirements.txt -r requirements-dev.txt
  - pip3 install -U codecov

env:
  global:
  - secure: "AMgOQ88RW5w0KVCrMBKPYogDPBFhBKBm2zIcJEzGi+fBVyhLvEz1X3+vOBt5rvxWIxzvObKMbdT2Nny4I2xNrHMqLiTNHU9ovT81rgfRa/VkgmxVWtjXz1Eu8xfFhL5suE+xVBvDKOM34ik9VunJs+Pnp2SlZACeOtaWuiyG+375g14VuUERVZy0wKaH0nBhYKp6WAugFZCDoFyw/FIdstRauAZQaT41Xy3oeFMsHDeXixDh/CFr7N1rnjgJ6GJiGRhHPaeNM7rP4B73yEIPvRXuDNAG3wS0bBd3sSWudId/g6BiZK5asOd7cJ0dpXLlsQ+AmbN5RIMMpIgw5t1E4ivI1iV/JEJ6Wohm7d7/K/I3yK3VcXd7ZVhFwpdarNq+6kcnfdQZpo0rd9arCoEAgYREQFigYeS1fnok5eYCJf4a+jaxAZSpIoipPJGUtnlUYvqezSULIfD4d5N26BN2gHOKnjdhs21tSqXh25j+HWcPjXfy3BH8cG1kkpZv9CguEZhIHnRU7jjrLHFjf+0PbTuHpxbB0AmVcnnYcPXwIpHbQqsdLGiMH+6Un3GS6EjalXB1ZxWu+hdlX0BuapR7cNYINZdi3uqp78MeTlsaYIl47vLMuRI3YpZVPxdN55xXdbiHZuIeX+gB6LaFiiCe6PAXv6kPJdGfzrrJFHLdGnE="
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: Mowp8q0AxgQKH/LrW9cOpSyxdZvaD/nhan3Y234sZ5PMZJGZmmoUipjsbzGtKXNWzMiBNIkp8AhDZ0YKrXueMz7T7ZFelMnLbskiIB0rqVDkhVUqwrY/ajtBS+QIDwDVsYk9iXWHVI/mkmbhefM9vpQkeF1892H6Q/lYcbf49UcHLGXZ+5crvZqijWjaGqQArveX0v8KjFFelEHwcog0YmvsS2E1TnDdvGrTL2LxrU2yrjo6Sk+f4Evv37dvfE+I5/UjuRIJ/jMBf4JGTijcwRX/iTqNqwqxnovJ5spYbt1qgTht7KGiiEbu1qy5xHRxKdn4rdq/lK44s0KbeDqfXDL1B2QHL4C13A16/mMn6rrJLEluv3JCpDx55f2Z4CiEWD7LfO71ssgB+A2zHuq05qmRAoqp3lqnLUindJc4KbhLwxOOmg8kI8aJ1SASdxrxp0rWiPbHfytvKP4pyHaxMDB3tfKNFmR/woJl8n8brD+wXnUI2JM4WUfqqtzHJrlk+aQxtAYkq822HyFA246s6352IDqqcqQovh9auZpUMCDfgPy0ngDJdfNESMEIDl5NTYrmtTVWdyKAYumJJzlIlejMffo3CDfIHrQZ9+4Gx7ABctKKNkNKCrgtKio6/uRjp0a4RtTfrqXQrFRlA4TBKVIDfX121ZF0n4yP8fDbZQw=

script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always

after_success:
  - codecov